### ISSUE TITLE
Add optional exclusion / configuration for an app

### ISSUE THREAD

**Issue by steveculshaw** [veler/CtrlHelpApp#11]
### What feature or new app's keyboard shortcut do you think should be added to CtrlHelp?

Add optional exclusion / configuration for an app

Basically someway to stop the "This app isn't supported..." dialog from appearing 

### Why do you think this is needed?

It's very annoying that the dialog appears :-(

I'm conscious that I tend to leave my little finger depressed on the CTRL key when I'm editing using the left & right arrows.
Then stop for a moment, leaving the CTRL depressed

... which triggers the dialog 

### Solution/Idea

Some sort of "Exclude from future checks" tick box in the dialog

**Comment by veler** [comment]
Hi,
Thanks for this feedback.

You can already exclude an app from the cheat sheet. To do this:
1. Make sure the app you want to ignore is running.
2. Open the Practice Mode in CtrHelp, then click the Settings button next to the search bar at the top of the window.
3. Scroll down to "Ignored apps" and expand it.
4. In `Add an application to ignore`, select the window corresponding to the want to want CtrlHelp to ignore.

![image](https://github.com/user-attachments/assets/2bd6fb75-9f52-4eda-b0bc-62cc5b107bb6)

I hope this help! :)

**Comment by steveculshaw** [comment]
Many thanks Etienne ... that worked a treat

**Comment by steveculshaw** [comment]
Feature already in app

**Comment by veler** [comment]
Glad it worked!
Now to myself : maybe add a button to the cheat sheet that says "never show the cheat sheet on this app again "

**Comment by veler** [comment]
Hello,
I just submitted a new update (1.0.3.0) that adds a button to ignore an app directly from the Cheat Sheet window. It will be available within ~48h.
Thanks !

**Comment by steveculshaw** [comment]
Nice one !!!
