### ISSUE TITLE
The Ignored App functionality doesn't seem to work in Remote Desktops

### ISSUE THREAD

**Issue by steveculshaw** [veler/CtrlHelpApp#12]
### Current behavior

The Ignored App functionality doesn't seem to work in Remote Desktops.

I have added an exclusion for Beyond Compare on my main PC.
This works fine when I hold CTRL while BC has the focus 

BUT when I remote desktop onto another of my PC, which also has Beyond Compare installed, and hold CTRL, the "This app isn't supported" dialog appears.
And what is really confusing is the remote PC does NOT have CtrlHelp installed ???

### How to reproduce it (as minimally and precisely as possible)

1. create an exclusion for the program, e.g. Beyond Compare
2. remote desktop to second PC without CtrlHelp installed, but does have Beyond Compare installed
3. open Beyond Compare through RDP on the second PC ...

### Expected behavior

The CtrlHelp dialog should not be displayed

### Screenshots

<img width="668" alt="bc-exclusion" src="https://github.com/user-attachments/assets/bc9a80cc-225e-40d6-a3f2-a5a01a00f948">

<img width="350" alt="ctrl-dialog-on-rdp" src="https://github.com/user-attachments/assets/3d3461ec-8000-4cf4-bcfb-aa2921e10af7">

### CtrlHelp Version

1.0.2.0 | X64 | Release

**Comment by veler** [comment]
Hi,

That's a slightly different issue than the previous one. CtrlHelp cannot know what app you are running in the RDP. What CtrlHelp detected is the window of the Remote Desktop.

The solution is to exclude the window of RDP in CtrlHelp. If you want CtrlHelp to work in certain apps within the RDP, you will need to install CtrlHelp in the Windows you are connected to through RDP.

**Comment by steveculshaw** [comment]
And again that fixed the issue 

Cheers
SteveC
